const express = require("express");
const router = express.Router();

const SPORTS = [
  "American Football",
  "Archery",
  "Artistic Gymnastics",
  "Athletics",
  "Australian Rules Football",
  "Badminton",
  "Bandy",
  "Baseball",
  "Basketball",
  "Beach Soccer",
  "Beach Volleyball",
  "Biathlon",
  "Billiards",
  "BMX",
  "Bobsleigh",
  "Bodybuilding",
  "Bowling",
  "Boxing",
  "Canoe Slalom",
  "Canoe Sprint",
  "Carrom",
  "Chess",
  "Cricket",
  "Croquet",
  "Curling",
  "Cycling",
  "Darts",
  "Decathlon",
  "Diving",
  "Dragon Boat",
  "Equestrian",
  "eSports",
  "Fencing",
  "Field Hockey",
  "Figure Skating",
  "Floorball",
  "Football",
  "Formula Racing",
  "Futsal",
  "Gaelic Football",
  "Golf",
  "Greco-Roman Wrestling",
  "Gymnastics",
  "Handball",
  "Horse Racing",
  "Hurling",
  "Ice Hockey",
  "Inline Skating",
  "Javelin Throw",
  "Judo",
  "Kabaddi",
  "Karate",
  "Kayaking",
  "Kho-Kho",
  "Kickboxing",
  "Korfball",
  "Lacrosse",
  "Lawn Bowls",
  "Long Jump",
  "Luge",
  "Marathon",
  "Mixed Martial Arts",
  "Modern Pentathlon",
  "Motorcycling",
  "Muay Thai",
  "Netball",
  "Obstacle Racing",
  "Open Water Swimming",
  "Padel",
  "Para Athletics",
  "Para Badminton",
  "Para Swimming",
  "Pickleball",
  "Polo",
  "Powerlifting",
  "Rowing",
  "Rugby League",
  "Rugby Sevens",
  "Rugby Union",
  "Sailing",
  "Sambo",
  "Sepak Takraw",
  "Shooting",
  "Short Track Speed Skating",
  "Skateboarding",
  "Ski Jumping",
  "Snooker",
  "Snowboarding",
  "Softball",
  "Speed Skating",
  "Sport Climbing",
  "Squash",
  "Surfing",
  "Swimming",
  "Table Tennis",
  "Taekwondo",
  "Tennis",
  "Triathlon",
  "Volleyball",
  "Water Polo",
  "Weightlifting",
  "Wrestling",
  "Wushu"
];

router.get("/", (req, res) => {
  res.json(
    SPORTS
      .slice()
      .sort((a, b) => a.localeCompare(b))
      .map((sport) => ({ sport_name: sport }))
  );
});

module.exports = router;
